### ISSUE TITLE
[Request] Alpha.dll is missing to execute the encrypt. And where can we buy the paid version?

### ISSUE THREAD

**Issue by Marshall13** [Paskowsky/DreamProtectorFree#2]
Hello,
This project is from 2017 so I hope it's still possible to get an answer ..: c
Dlls are missing to make this encrypt work; So I do not know if it's possible to add them on your side :)
![image](https://user-images.githubusercontent.com/21182039/42686276-b0020c4a-8695-11e8-9f56-955fa3ab57f0.png)
![image](https://user-images.githubusercontent.com/21182039/42686299-bcd47430-8695-11e8-92cb-42f348ee9dce.png)
The error says: "Can not open file: 'C:/Users/Marshall/[...]/alpha.dll' "

Nevertheless, the source is very interesting, and it tempts me a lot to buy the paid version! Where can we go to talk about it? :)
cordially

**Comment by Paskowsky** [comment]
You are compiling as release so it will search for library source named "alpha.dll"

Look at source code [https://github.com/Paskowsky/DreamProtectorFree/blob/ee8cef0a5694c9096ef22f88e38667499854b375/Dream%20Protector%20Free/Protector.cs#L138](url)

You should copy "D.cs" in "Release" folder and rename it as alpha.dll
